### ISSUE TITLE
ClassCastException

### ISSUE THREAD

**Issue by jsongHBO** [endgameinc/storm-metrics-statsd#8]
Hi, 
I'm new to java and storm.  But I'm getting this exception trying to use your library.  

```
2014-09-05 17:01:33 INFO  executor:0 - Finished loading executor __metricscom.endgame.storm.metrics.statsd.StatsdMetricConsumer:[40 40]
2014-09-05 17:01:33 INFO  executor:0 - Preparing bolt __metricscom.endgame.storm.metrics.statsd.StatsdMetricConsumer:(40)
2014-09-05 17:01:33 ERROR util:0 - Async loop died!
java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Integer
at com.endgame.storm.metrics.statsd.StatsdMetricConsumer.parseConfig(StatsdMetricConsumer.java:80)
at com.endgame.storm.metrics.statsd.StatsdMetricConsumer.prepare(StatsdMetricConsumer.java:64)
at backtype.storm.metric.MetricsConsumerBolt.prepare(MetricsConsumerBolt.java:49)
at backtype.storm.daemon.executor$fn__3352$fn__3364.invoke(executor.clj:690)
at backtype.storm.util$async_loop$fn__452.invoke(util.clj:429)
at clojure.lang.AFn.run(AFn.java:24)
at java.lang.Thread.run(Thread.java:745)
```

I've done everything correctly to my knowledge.  So I did a little test.

```
    Config cong = new Config(); 
    Map statsdConfig = new HashMap();
    statsdConfig.put(StatsdMetricConsumer.STATSD_HOST, Common.STATSD_HOST);
    statsdConfig.put(StatsdMetricConsumer.STATSD_PORT, new Integer(8126));  // I've also tried raw 8126
    statsdConfig.put(StatsdMetricConsumer.STATSD_PREFIX, Common.STATSD_PREFIX);
    // This foo does NOT throw exception.  !!!!
    int foo = (Integer) statsdConfig.get(StatsdMetricConsumer.STATSD_PORT);
    conf.registerMetricsConsumer(StatsdMetricConsumer.class, statsdConfig, 2);
```

So, why would my int foo not throw exception but the metric-statsd one does?  I found out that clojure would convert int into long http://stackoverflow.com/questions/9457537/why-does-int-10-produce-a-long-instance  
Yet, this is supposed to be fixed in clojure 1.5+    the current version of storm I'm using, 0.9.2-incubating, is using clojure 1.5.1     http://repo1.maven.org/maven2/org/apache/storm/storm/0.9.2-incubating/storm-0.9.2-incubating.pom

Have you guys seen problem like this?  Perhaps making it like this would help

```
statsdPort = ((Long) conf.get(STATSD_PORT)).intValue();
```

**Comment by jatrost** [comment]
I haven't used Storm in a while so I haven't seen this error.  It looks like a relatively straightforward fix though:

https://github.com/endgameinc/storm-metrics-statsd/blob/master/src/main/java/com/endgame/storm/metrics/statsd/StatsdMetricConsumer.java#L80

```
        if (conf.containsKey(STATSD_PORT)) {
            statsdPort = (Integer) conf.get(STATSD_PORT);
        }
```

to

```
        if (conf.containsKey(STATSD_PORT)) {
            statsdPort = ((Long) conf.get(STATSD_PORT)). intValue();
        }
```

Can you try this?  If it works, then make a PR.

**Comment by jsongHBO** [comment]
#9 PR out
